APM-3013689: Added validation of parameters from activation-config.yaml
dynatrace-oss/dynatrace-gcp-function pull request #103
Opened 2021-05-24 08:22 UTC by mswiatkowska

+ added missing parameters

2021-05-24 09:16 UTC, sq2gxo approved these changes

2021-05-24 09:31 UTC, dtwwolinski requested changes

2021-05-24 09:31 UTC, dtwwolinski commented on scripts/setup.sh
> +    echo "Dyntrace url secret creation failed"
````suggestion
echo "Dynatrace url secret creation failed"
````

2021-05-24 09:31 UTC, dtwwolinski approved these changes

2021-05-24 09:32 UTC, dtwwolinski submitted a review, later dismissed

2021-05-25 07:25 UTC, pgutkowski approved these changes

2021-05-25 08:16 UTC, sq2gxo approved these changes

2021-05-25 09:51 UTC, merged