APM-306505 Cleanup gcp-function GitHub documentation
dynatrace-oss/dynatrace-gcp-function pull request #111
Opened 2021-06-07 21:58 UTC by dtwwolinski

- Added link to Azure monitoring

2021-06-08 07:05 UTC, pgutkowski requested changes

2021-06-08 07:05 UTC, pgutkowski commented on README.md
If we are adding links to other log forwarding solutions, add AWS log forwarder too, please

2021-06-09 05:21 UTC, pgutkowski approved these changes

2021-06-09 08:06 UTC, mswiatkowska approved these changes

2021-06-09 10:20 UTC, Dawid-Kaszubski approved these changes

2021-06-09 11:41 UTC, Dawid-Kaszubski approved these changes

2021-06-09 11:51 UTC, merged