Added importing self monitoring dashboard on container start
dynatrace-oss/dynatrace-gcp-function pull request #140
Opened 2021-07-19 08:26 UTC by Dawid-Kaszubski

2021-07-19 17:03 UTC, dtwwolinski requested changes

2021-07-19 17:03 UTC, dtwwolinski commented on src/lib/self_monitoring.py
> +    dashboard_file_path = os.path.dirname(os.path.realpath(__file__)).join("../config").join(dashboard_filename)
Shouldn't the dashboard file be taken from **dashboard** folder instead of **config**?

2021-07-20 05:40 UTC, mswiatkowska commented on src/run_docker.py
> +loop.run_until_complete(import_self_monitoring_dashboards())
missing metadata parameter?

2021-07-20 05:48 UTC, mswiatkowska commented on src/lib/self_monitoring.py
> +        context.log(f"Failed to create self monitoring dashboard for due to '{response_body}'")
(minor) unnecessary 'for'?

2021-07-20 18:00 UTC, dtwwolinski approved these changes

2021-07-21 05:40 UTC, mswiatkowska approved these changes

2021-07-21 05:41 UTC, karolkieglerski approved these changes

2021-07-21 06:22 UTC, sq2gxo approved these changes

2021-07-22 08:11 UTC, merged