fix for dynatrace manged urls
dynatrace-oss/dynatrace-gcp-function pull request #24
Opened 2020-10-30 15:35 UTC by pawelsiwek

Fix to support URL's in Dynatrace managed format: https://abcd.managed-dt.dynalabs.io/e/ett29184-1ae2-46dd-96fe-02957773fc57/ 
Using urljoin removes all URL segments .. :(

2020-11-02 13:48 UTC, sq2gxo approved these changes

2020-11-02 13:50 UTC, sq2gxo commented on scripts/setup.sh
> +echo "Please log in to Dynatrace, and generate API token (Settings->Integration->Dynatrace API). The token requires grant of 'API v2 Ingest metrics', 'API v1 Read configuration' and 'WriteConfig' sco
"Read configuration' and 'WriteConfig' scope" -> "'Read configuration' and 'Write configuration' scope"?

2020-11-03 06:37 UTC, pgutkowski requested changes

2020-11-03 06:37 UTC, pgutkowski commented on src/lib/metric_ingest.py
> +        url=f"{context.dynatrace_url}/api/v2/metrics/ingest",
If we want to do a simple string appending, then we need to handle double slash case - if `context.dynatrace_url` ends with `/`, then result path has empty URL segment and Dynatrace server returns 404.

Something like that should work
```suggestion
        url=f"{context.dynatrace_url.rstrip('/')}/api/v2/metrics/ingest",
```

2020-11-03 15:03 UTC, pgutkowski approved these changes

2020-11-03 15:04 UTC, merged