Added vpcNetwork parameter
dynatrace-oss/dynatrace-gcp-function pull request #315
Opened 2022-07-25 12:41 UTC by joaquinfilipic-dynatrace

Added vpcNetwork param to values.yaml, with default value, so the customer can select in which network to deploy the autopilot cluster

2022-07-25 12:57 UTC, equardo approved these changes

2022-07-25 13:50 UTC, tepesware requested changes

2022-07-25 13:50 UTC, tepesware commented on k8s/helm-chart/dynatrace-gcp-function/values.yaml
> +# vcpNetwork: name of an existing VPC Network in which the autopilot cluster will be deployed. By default, the network named 'default' is used
```suggestion
# vcpNetwork: name of an existing VPC Network in which the autopilot cluster will be deployed. By default or when empty, the network named 'default' is used
```

2022-07-25 14:36 UTC, tepesware approved these changes
It's me Wlad ;)

2022-07-26 08:39 UTC, Dawid-Kaszubski approved these changes

2022-07-26 08:39 UTC, equardo approved these changes

2022-07-26 09:34 UTC, merged