Apm 294693 introduce metrics dimension filters
dynatrace-oss/dynatrace-gcp-function pull request #98
Opened 2021-05-17 09:02 UTC by sq2gxo

2021-05-19 10:07 UTC, pgutkowski submitted a review, later dismissed

2021-05-19 14:07 UTC, Dawid-Kaszubski approved these changes

2021-05-19 14:19 UTC, dtwwolinski requested changes

2021-05-19 14:19 UTC, dtwwolinski commented on src/config/pubsub_subscription.yml
> +  gcp_monitoring_filter: var:filter_conditions
Double entries.

2021-05-19 20:34 UTC, dtwwolinski submitted a review, later dismissed

2021-05-20 06:59 UTC, mswiatkowska commented on src/config/vpn_gateway.yml
>  gcp:
missing `gcp_monitoring_filter: var:filter_conditions` ?

2021-05-20 07:49 UTC, sq2gxo commented on src/config/vpn_gateway.yml
>  gcp:
good catch! featureSet was also missing

2021-05-20 07:56 UTC, Dawid-Kaszubski approved these changes

2021-05-20 07:58 UTC, mswiatkowska approved these changes

2021-05-20 08:01 UTC, merged